apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-logging
  namespace: core-stage-lms-namespace
data:
  fluent.conf: |
    <source>
      @type tail
      path /var/log/containers/*.log
      pos_file /var/log/es-containers.log.pos
      tag raw.kubernetes.*
      read_from_head true
      <parse>
        @type json
      </parse>
    </source>
